ssl:
  client-auth: true
  keystore-path: identity.jks
  keystore-password: secret
  truststore-path: truststore.jks
  truststore-password: secret

spring:
  grpc:
    server:
      port: 8443
      ssl:
        enabled: true
        client-auth: require
        secure: true
        bundle: "reloadable-ssl-bundle"